stages:
  - install
  - build
  - test

# TODO: Add document & version bump stage as well
# TODO: Add publish stage on main branch as well

install-job:
  stage: install
  script:
    - npm i -g npx
    - npx yarn

build-job:
  stage: build
  script:
    - npm run build

lint-test-job:
  stage: test
  script:
    - npm run lint

type-test-job:
  stage: test
  script:
    - npm run typecheck

# TODO: ADD UNIT TESTS AS WELL
