image: node:19.2

definitions:
  steps:
    - step: &install-deps
        name: install deps
        caches:
          - node
        script:
          - yarn --frozen-lockfile
    - step: &eslint
        name: eslint
        caches:
          - node
        script:
          - yarn run eslint
    - step: &stylelint
        name: stylelint
        caches:
          - node
        script:
          - yarn run stylelint
    - step: &typecheck
        name: typecheck
        caches:
          - node
        script:
          - yarn run typecheck
    - step: &create-artifact
        name: Create artifact
        script:
          - git archive --format=tar.gz main -o application.tar.gz
        artifacts:
          - application.tar.gz
    - step: &deploy-artifact
        name: Deploy to heroku
        deployment: production
        caches:
          - node
        script:
          - pipe: atlassian/heroku-deploy:2.0.0
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: "application.tar.gz"
    - step: &bump-document-release
        name: Bump version, document and publish
        caches:
          - node
        script:
          - yarn run release
pipelines:
  default:
    - step: *install-deps
    - parallel:
        - step: *eslint
        - step: *stylelint
        - step: *typecheck
  branches:
    main:
      # we should also bump the version & add documentation from conventional commit messages before publishing/deploying
      - step: *install-deps
      - step: *create-artifact
      - step: *bump-document-release
      - step: *deploy-artifact
