image: node:19.2

pipelines:
  default:
    - step:
        name: install deps
        caches:
          - node
        script:
          - npm ci
    - parallel:
        - step:
            name: eslint
            caches:
              - node
            script:
              - npm run eslint
        - step:
            name: stylelint
            caches:
              - node
            script:
              - npm run stylelint
        - step:
            name: typecheck
            caches:
              - node
            script:
              - npm run typecheck
  #branches:
  #  master:
  #    - parallel:
  #        - step:
  #            name: Build and Test
  #            caches:
  #              - node
  #            script:
  #              - npm install
  #              - npm test
  #        - step:
  #            name: Security Scan
  #            script:
  #              # Run a security scan for sensitive data.
  #              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
  #              - pipe: atlassian/git-secrets-scan:0.5.1
  #    - step:
  #        name: Deploy to Production
  #        deployment: Production
  #        script:
  #          # Bump versions before publishing
  #          - npm --no-git-tag-version version "1.0.$BITBUCKET_BUILD_NUMBER" -m "Upgrade to new version"
  #          # Publish package
  #          - pipe: atlassian/npm-publish:0.3.2
  #            variables:
  #              NPM_TOKEN: $NPM_TOKEN
